# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Publish container

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: devcontainer-ubuntu-egl-desktop-base
  USER_IMAGE_NAME: devcontainer-ubuntu-egl-desktop

jobs:
  build-base:
    name: Build and push base image - Ubuntu ${{ matrix.os_version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
        - os_version: "20.04"
        - os_version: "22.04"
        - os_version: "24.04"
          latest_tag: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch commit time
      run: echo "COMMIT_TIME_GIT=$(TZ=UTC git show -s --format='%cd' --date=format-local:'%Y%m%d%H%M%S')" >> "$GITHUB_ENV"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract container metadata for base image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}

    - name: Build and push base image - Ubuntu ${{ matrix.os_version }}
      uses: docker/build-push-action@v5
      with:
        build-args: |
          DISTRIB_RELEASE=${{ matrix.os_version }}
        context: .
        file: ./files/Dockerfile.base
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ matrix.os_version }}-buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ matrix.os_version }}-buildcache,mode=max
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ matrix.os_version }}
          ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ matrix.os_version }}-${{ env.COMMIT_TIME_GIT }}
          ${{ matrix.latest_tag && format('{0}/{1}:latest', env.REGISTRY, env.BASE_IMAGE_NAME) || '' }}

  build-user:
    name: Build and push user image - Ubuntu ${{ matrix.os_version }}
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
        - os_version: "20.04"
        - os_version: "22.04"
        - os_version: "24.04"
          latest_tag: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch commit time
      run: echo "COMMIT_TIME_GIT=$(TZ=UTC git show -s --format='%cd' --date=format-local:'%Y%m%d%H%M%S')" >> "$GITHUB_ENV"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract container metadata for user image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.USER_IMAGE_NAME }}

    - name: Build and push user image - Ubuntu ${{ matrix.os_version }}
      uses: docker/build-push-action@v5
      with:
        build-args: |
          BASE_IMAGE=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ matrix.os_version }}
          USER_NAME=user
          USER_UID=1000
          USER_GID=1000
          USER_PASSWORD=ubuntu
        context: .
        file: ./files/Dockerfile.user
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.USER_IMAGE_NAME }}:${{ matrix.os_version }}
          ${{ env.REGISTRY }}/${{ env.USER_IMAGE_NAME }}:${{ matrix.os_version }}-${{ env.COMMIT_TIME_GIT }}
          ${{ matrix.latest_tag && format('{0}/{1}:latest', env.REGISTRY, env.USER_IMAGE_NAME) || '' }}
